### ISSUE TITLE
WebDAV support for events

### ISSUE THREAD

**Issue by ThatOneCalculator** [eeec-cal/eeec#1]
This would actually be incredibly awesome and useful (already is very awesome) if I could hook it into WebDAV to sync with my online calendar :D

**Comment by eeec-cal** [comment]
I'm very sorry, but I don't know about WebDAV at all. Can you tell me about it? I would be very grateful to help you :D

**Comment by ThatOneCalculator** [comment]
It's basically a protocol set (extended by CalDAV which I should've mentioned, CardDav, etc) that allows sharing calendar information over HTTP(S). There's a great write-up here:
 https://www.linux-magazine.com/Issues/2020/235/Using-CalDAV-CardDAV-to-manage-calendars-and-address-books

And using the `vdirsyncer` command line utility might be the simplest and easiest way to use CalDAV

**Comment by eeec-cal** [comment]
Ohhh, I don't know if eeec is compatible with this. Eeec is just basically a `cal` front-end, and I think `cal` would suit your needs more. I am very sorry :(
